# Generated by Django 2.0.7 on 2018-08-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_project_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slack_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
