# Generated by Django 2.0.7 on 2018-08-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180809_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AlterField(
            model_name='user',
            name='slack_id',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
