# Generated by Django 2.0.7 on 2018-08-03 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_project_team'),
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Resolved'), ('P', 'Pending'), ('C', 'Closed')], default='P', max_length=20)),
                ('issue', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('hours', models.CharField(max_length=10)),
                ('is_edited', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.AddField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[('1', 'DONE'), ('2', 'WIP')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='issue',
            name='scrum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.Scrum'),
        ),
        migrations.AddField(
            model_name='log',
            name='scrum',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scrum.Scrum'),
        ),
    ]
