# Generated by Django 2.0.7 on 2018-07-18 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[('DONE', '1'), ('WIP', '2'), ('ISSUES', '3'), ('HOURS', '4')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
