# Generated by Django 2.0.7 on 2018-07-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_auto_20180718_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
