# Generated by Django 2.0.7 on 2018-08-08 22:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_auto_20180803_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrum',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 22, 0, 42, 601122, tzinfo=utc)),
        ),
    ]
