# Generated by Django 2.0.7 on 2018-07-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_auto_20180720_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
