# Generated by Django 2.0.7 on 2018-07-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_project_team'),
        ('scrum', '0004_auto_20180720_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Project'),
            preserve_default=False,
        ),
    ]
