# Generated by Django 2.0.7 on 2018-08-08 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_auto_20180809_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrum',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
