# Generated by Django 2.0.7 on 2018-08-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0005_auto_20180809_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrum',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
