# Generated by Django 2.0.7 on 2018-07-24 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0005_auto_20180721_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='scrum',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scrum.Scrum'),
            preserve_default=False,
        ),
    ]
