# Generated by Django 2.0.7 on 2018-07-25 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_project_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrum', '0006_auto_20180724_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='project',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='log',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='log',
            name='project',
        ),
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.AddField(
            model_name='issue',
            name='scrum',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scrum.Scrum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrum',
            name='hours',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrum',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrum',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[('1', 'DONE'), ('2', 'WIP')], max_length=10),
        ),
    ]
