# Generated by Django 2.0.7 on 2018-08-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0006_auto_20180809_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrum',
            name='hours',
            field=models.FloatField(),
        ),
    ]
