# Generated by Django 2.0.7 on 2018-07-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0007_auto_20180725_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
