# Generated by Django 2.0.7 on 2018-10-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0007_auto_20180814_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrum',
            name='minutes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]


