# Generated by Django 2.0.7 on 2018-07-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0008_issue_is_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='is_urgent',
            field=models.CharField(default='false', max_length=20),
        ),
    ]
