# Generated by Django 2.0.7 on 2018-10-08 06:42

from django.db import migrations


def transfer_hours_to_minutes(apps, schema_editor):
    # We can't import the Scrum model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Scrum = apps.get_model('scrum', 'Scrum')
    for scrum in Scrum.objects.all():
       # Since a float maybe '8.2', We need to make suer it has two decimals
       #  so it won't be lost when it is converted into an integer
       hours = '{0:.2f}'.format(scrum.hours)
       list_time = hours.split(".")
       # Convert hours into minutes
       final_minutes = int(list_time[0]) * 60
       # Add the remaining minutes to the converted hours
       final_minutes += int(list_time[1])
       scrum.minutes = final_minutes
       # Define what fields are updated so it won't update the time
       scrum.save(update_fields=['minutes'])

class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0008_auto_20181008_1435'),
    ]

    operations = [
        migrations.RunPython(transfer_hours_to_minutes)
    ]
