# Generated by Django 2.0.7 on 2018-07-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0009_auto_20180727_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
