# Generated by Django 2.0.7 on 2018-10-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0009_auto_20181008_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrum',
            name='hours',
        ),
    ]
