# Generated by Django 2.0.7 on 2018-07-30 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0010_auto_20180727_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
