# Generated by Django 2.0.7 on 2018-07-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0011_issue_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='date_created',
        ),
    ]
